import { Product } from '@/types';

// Mock data từ SQL trong supabase-note.md
export const mockProducts: Product[] = [
  {
    id: 'gami-core',
    name: 'Ghế Gami Core',
    description: 'Ghế công thái học Gami Core, thiết kế hiện đại, hỗ trợ tư thế ngồi tối ưu.',
    price: 2050000,
    original_price: 2250000,
    discount_percentage: 9,
    image_url: 'https://product.hstatic.net/200000912647/product/1_e71646180bb44ce6bd7b4515caace2ee_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 4.5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-crom-all-black',
    name: 'Ghế Gami Crom (Bản All Black)',
    description: 'Ghế công thái học Gami Crom phiên bản All Black, thiết kế sang trọng, đẳng cấp.',
    price: 5990000,
    original_price: 6390000,
    discount_percentage: 6,
    image_url: 'https://product.hstatic.net/200000912647/product/1_5b197650a67f428b87eeed2ce712480f_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-crom-carbon',
    name: 'Ghế Gami Crom (Phiên bản lưng Carbon)',
    description: 'Ghế công thái học Gami Crom phiên bản lưng Carbon, nhẹ và chắc chắn, hỗ trợ lưng tối đa.',
    price: 6890000,
    original_price: 7290000,
    discount_percentage: 5,
    image_url: 'https://product.hstatic.net/200000912647/product/6_7256181dc0e040518daaaf210464741f_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 4.8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-crom-pro',
    name: 'Ghế Gami Crom Pro',
    description: 'Ghế công thái học Gami Crom Pro, phiên bản cao cấp nhất, tích hợp nhiều tính năng hiện đại.',
    price: 12900000,
    original_price: 13500000,
    discount_percentage: 4,
    image_url: 'https://product.hstatic.net/200000912647/product/crom_pro__1__d1e41a2442e84df1b2d7ae01cdcd883d_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-focus-v1',
    name: 'Ghế Gami Focus V1',
    description: 'Ghế công thái học Gami Focus V1, thiết kế tập trung vào sự thoải mái và hỗ trợ lưng.',
    price: 2690000, 
    original_price: 2990000,
    discount_percentage: 10,
    image_url: 'https://product.hstatic.net/200000912647/product/7_ef0717654a27469f993e2556267da3e1_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 4.3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-focus-v2',
    name: 'Ghế Gami Focus V2 Full lưới',
    description: 'Ghế công thái học Gami Focus V2 Full lưới, thoáng mát và hỗ trợ tối đa tư thế ngồi.',
    price: 3590000,
    original_price: 3890000, 
    discount_percentage: 8,
    image_url: 'https://product.hstatic.net/200000912647/product/1_7c74b7ffccb54152ad0ac3272f18d5ff_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 4.6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'gami-metic',
    name: 'Ghế Gami Metic',
    description: 'Ghế công thái học Gami Metic, thiết kế thông minh, hỗ trợ cột sống và giảm mỏi khi ngồi lâu.',
    price: 4490000,
    original_price: 4790000,
    discount_percentage: 6,
    image_url: 'https://product.hstatic.net/200000912647/product/1_7c6dda169db045579b693faf7fb8e409_large.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Gami',
    brand: 'Gami Việt Nam',
    rating: 4.7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'dvary-butterfly',
    name: 'Ghế công thái học Dvary Butterfly',
    description: 'Ghế công thái học ergonomic Dvary Butterfly chính hãng code VN tặng kèm phụ kiện. Bảo hành 5 năm, sản xuất chính hãng GT chair.',
    price: 13500000,
    original_price: 17500000,
    discount_percentage: 23,
    image_url: 'https://congthaihoc.vn/wp-content/uploads/2021/10/The%CC%82m-tie%CC%82u-de%CC%82%CC%80-phu%CC%A3-23-600x600.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'GTchair',
    brand: 'GT Chair',
    rating: 4.8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'ergohuman-classic',
    name: 'Ghế công thái học Ergohuman Classic',
    description: 'Ghế công thái học ergonomic Ergohuman bản Classic với thiết kế tinh tế, hỗ trợ tư thế ngồi tối ưu. Bảo hành 3 năm chính hãng.',
    price: 11500000,
    original_price: 12500000,
    discount_percentage: 8,
    image_url: 'https://congthaihoc.vn/wp-content/uploads/2021/10/The%CC%82m-tie%CC%82u-de%CC%82%CC%80-phu%CC%A3-23-600x600.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Ergohuman',
    brand: 'Ergohuman',
    rating: 4.7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'felix-6232a',
    name: 'Ghế công thái học Felix 6232A',
    description: 'Ghế công thái học Ergonomic Felix 6232A phù hợp với người từ 1m65. Miễn phí vận chuyển và lắp đặt nội thành Hà Nội và TP HCM.',
    price: 2900000,
    original_price: 3200000,
    discount_percentage: 9,
    image_url: 'https://congthaihoc.vn/wp-content/uploads/2021/10/The%CC%82m-tie%CC%82u-de%CC%82%CC%80-phu%CC%A3-23-600x600.png',
    category_id: 'ghe-cong-thai-hoc',
    brand_id: 'Felix',
    brand: 'Felix',
    rating: 4.3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
]; 